feat: change kernel parameter handling
filecoin-project/rust-gpu-tools pull request #40
Opened 2021-07-05 15:37 UTC by vmx

BREAKING CHANGE: Kernel creation takes different parameter values now.

Defining the global work size now follows the CUDA model and no longer
the OpenCL model. In OpenCL the global work size is the total number
of threads. In CUDA it is the number of thread groups of local work
size.

This change is made, so that the same kernel creation code can be run
indepent of whether OpenCL or CUDA is used.

2021-07-06 10:44 UTC, dignifiedquire requested changes

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/error.rs
> +    ParseId(String),
maybe better `InvalidId`?

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +pub const CL_UUID_SIZE_KHR: usize = 16;
can you add a comment what this exactly is?

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +/// It is the first two identifiers of e.g. `lcpci`:
typo, should be `lspci`

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +            hex::encode(&self.0[..4]),
does this do padding? It looks like those UUIDs are padded in some form

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +        self.pci_id == other.pci_id && self.uuid == other.uuid
shouldn't the vendor and the name at least be checked as well?

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +    pub fn cl_device_id(&self) -> cl_device_id {
comment?

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +    pub fn by_unique_id(unique_id: UniqueId) -> GPUResult<&'static Device> {
comment

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +    pub fn by_uuid(uuid: DeviceUuid) -> GPUResult<&'static Device> {
comment

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +    pub fn by_pci_id(pci_id: PciId) -> GPUResult<&'static Device> {
commenet

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/mod.rs
> +    pub fn create_kernel(
best to add a note, how the local and global are used to calculate the total number in the opencl case

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/utils.rs
> +/// It is the first two identifiers of e.g. `lcpci`:
typo

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/utils.rs
> +        .expect("opencl3 returned an invalid UUID");
panic bad, are you sure this never happens?

2021-07-06 10:44 UTC, dignifiedquire commented on src/opencl/utils.rs
> +    let mut enumerated_device: u16 = 4660;
what if both are the case, the code should probably check at least for conflicts with any existing PCI-ID

2021-07-06 15:26 UTC, vmx reviewed
I've also addressed the comments that were meant for that other PR.

2021-07-07 09:22 UTC, dignifiedquire commented on src/opencl/mod.rs
> +            hex::encode(&self.0[..4]),
yeah that’s what I meant,

2021-07-08 11:29 UTC, vmx commented
@dignifiedquire I've rebased that one, it should now be way easier to review as it actually is quite a small change :)

2021-07-08 11:44 UTC, dignifiedquire approved these changes

2021-07-08 11:55 UTC, merged